### ISSUE TITLE
xenForo (nope)

### ISSUE THREAD

**Issue by Super35** [MineCode-Devs/Web-biz#2]
Xenforo The Best Forums Maker ever

[XENFORO](https://www.xenforo.com)

Almost all MCPE Softwares use it

PM and IM use it

it Has Custom Domain Name too

**Comment by Ad5001** [comment]
Do you know that it cost like $140 a year ?

**Comment by Taki21** [comment]
Wasting our time. That's not a website maker its a forums hoster we obviously see that PM and IM use it...
